@extends('layouts.admin')
@section('title','Newsletter')
@section('content')
<div class="heading"><h1>Newsletter</h1><p>Abonnés privés et campagnes. Mode : {{ config('newsletter.mode')==='preview'?'simulation sans envoi réel':'messagerie SMTP' }}.</p></div>
<div class="actions"><a class="button" href="{{ route('newsletter.create') }}">Rédiger une newsletter</a><a class="button secondary" href="{{ route('newsletter.form','fr') }}">Formulaire public</a></div>
<section class="card newsletter-admin-section"><h2>Abonnés</h2><p>Seules les adresses confirmées reçoivent une campagne. La liste est réservée aux administrateurs actifs.</p>
<ul class="newsletter-list">@forelse($subscribers as $s)<li><span>{{ $s->email }}</span><span>{{ ['pending'=>'Confirmation attendue','subscribed'=>'Inscription confirmée','unsubscribed'=>'Désinscrit'][$s->status] }} · {{ strtoupper($s->locale) }}</span><details><summary>Supprimer cette adresse</summary><p>Cette action efface l’adresse et ses messages de la liste. Les messages déjà remis au serveur ne peuvent pas être rappelés.</p><form method="post" action="{{ route('newsletter.subscriber.delete',$s) }}">@csrf @method('delete')<button type="submit" class="secondary">Confirmer la suppression</button></form></details></li>@empty<li>Aucun abonné.</li>@endforelse</ul>{{ $subscribers->withQueryString()->links('newsletter.pagination', ['label'=>'Pages des abonnés']) }}</section>
<section class="card newsletter-admin-section"><h2>Mes campagnes</h2><ul class="newsletter-list">@forelse($campaigns as $c)<li><a href="{{ route('newsletter.edit',$c) }}">{{ $c->subject }}</a><span>{{ ['draft'=>'Brouillon','approved'=>'Traitement autorisé','cancelled'=>'Arrêtée'][$c->status] }}</span></li>@empty<li>Aucune campagne.</li>@endforelse</ul>{{ $campaigns->withQueryString()->links('newsletter.pagination', ['label'=>'Pages de mes campagnes']) }}</section>
<section class="card newsletter-admin-section"><h2>Traitements récents</h2>@if(config('newsletter.mode')==='preview')<form method="post" action="{{ route('newsletter.simulate') }}">@csrf<button type="submit">Traiter la simulation</button></form>@endif<p>« Remis au serveur » ne garantit pas la réception dans la boîte du destinataire. Un état à vérifier n’est jamais réessayé automatiquement.</p><ul class="newsletter-list">@forelse($deliveries as $d)<li><span>{{ $d->kind==='confirmation'?'Confirmation d’adresse':'Campagne' }} · {{ ['pending'=>'En attente','sending'=>'En cours / à vérifier si interrompu','simulated'=>'Simulé, aucun envoi','handed_off'=>'Remis au serveur','needs_review'=>'À vérifier, pas de réessai automatique','cancelled'=>'Annulé'][$d->status] }}</span>@if(config('newsletter.mode')==='preview')<a href="{{ route('newsletter.delivery',$d) }}">Voir le message de test</a>@endif</li>@empty<li>Aucun message.</li>@endforelse</ul></section>
@endsection
